# Generated by Django 3.1.4 on 2021-02-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_uel_web',
            new_name='video_url_web',
        ),
    ]
