# Generated by Django 3.1.4 on 2021-02-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210215_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url_web',
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(max_length=32),
        ),
    ]
