# Generated by Django 3.1.4 on 2021-03-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_video_video_url_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url_web',
        ),
    ]
